version: "3.9"

services:
  reverse-proxy:
    image: traefik:v2.7
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/traefik.yaml
      - ./acme.json:/acme.json
      - ./traefik.log:/traefik.log

  prueba-gudfy:
    image: nestorsanchezz/prueba-gudfy:latest
    labels:
      - traefik.http.routers.prueba-gudfy.tls.certresolver=myresolver
      - traefik.http.routers.prueba-gudfy.rule=(Host(`${DOMAIN:-sancheznestor.com}`) || Host(`www.${DOMAIN:-sancheznestor.com}`))

volumes:
  dbdata:
